---
name: emu
channels:
  - conda-forge
  - nvidia/label/cuda-11.3.1
  - pytorch
dependencies:
  #- cuda-nvcc
  - cudatoolkit-dev=11.3
  - cupy
  - cython
  - h5py
  - joblib
  - matplotlib
  - numpy=1.23.5
  - nvitop
  - pandas
  - pillow
  - pip
  - pydantic
  - pyfftw=0.12.0
  - pyopengl
  - pyopenssl
  - pyqt
  - pyqt5-sip
  - pyqtgraph
  - pyqtwebengine
  - pytest
  - python=3.8
  - pytorch
  - pywavelets
  - pyyaml
  - qtconsole
  - readline
  - requests
  - responses
  - ruamel.yaml
  - scikit-image
  - scikit-learn
  - scikit-video
  - scipy
  - setuptools
  - torchvision
  - traitlets
  - urllib3=1.26.15
  - wheel
  - pip:
      - git+https://github.com/cortex-lab/phy.git
      - spikeinterface
