---
name: emusort
channels:
  - conda-forge
  - pytorch
dependencies:
  - cudatoolkit
  - cxx-compiler
  - cython
  - h5py
  - hdbscan
  - ipympl
  - ipywidgets
  - joblib
  - jupyter
  - libxcb
  - loky
  - matplotlib
  - networkx
  - numba
  - numpy
  - pandas
  - pip
  - pybind11
  - pyqt=5 
  - pyqt5-sip
  - pyqtwebengine
  - pyqtgraph
  - python=3.11 # phy gui makes py311 the maximum, due to imp dependency
  - pytorch
  - torchvision
  - torchaudio
  - ruamel.yaml
  - scikit-learn
  - scipy
  - tqdm
  - xarray
  - zarr
  - pip:
        - "-e ./sorting/spikeinterface" # install local spikeinterface for EMUsort
        - "-e ./sorting/Kilosort4" # install local Kilosort4 for EMUsort
        - git+https://github.com/cortex-lab/phy.git # latest version of phy from GitHub
