---
name: emusort
channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - cudatoolkit=11.6
  - cuda-version=11.6
  - cupy
  - cython
  - dask
  - h5py
  - joblib
  - matplotlib
  - numpy
  - nvitop
  - pandas
  - pillow
  - pip
  - pydantic
  - pyfftw
  - pyopengl
  - pyopenssl
  - pyqt
  - pyqt5-sip
  - pyqtgraph
  - pyqtwebengine
  - pytest
  - python=3.10
  - pytorch-gpu=1.13
  - pytorch-cuda=11.6
  - pywavelets
  - pyyaml
  - qtconsole
  - readline
  - requests
  - responses
  - ruamel.yaml
  - scikit-image
  - scikit-learn
  - scikit-video
  - scipy
  - setuptools
  - torchvision
  - traitlets
  - urllib3
  - wheel
  - pip:
      - git+https://github.com/cortex-lab/phy.git
      - spikeinterface
      - -e ./sorting/Kilosort4
